import {
  IsString,
  IsOptional,
  IsBoolean,
  IsEnum,
  IsUUID,
  IsDateString,
  IsInt,
  MaxLength,
  Min,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { ProductType } from '../../common/types/prisma-types';

// =============================================================================
// CREATE DTO - For creating products (local scope by default)
// =============================================================================
export class CreateProductDto {
  @ApiPropertyOptional({ description: 'UUID generated by client (optional)' })
  @IsOptional()
  @IsUUID()
  id?: string;

  @ApiProperty({ description: 'Product name (French)' })
  @IsString()
  @MaxLength(255)
  nameFr: string;

  @ApiPropertyOptional({ description: 'Product name (English)' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  nameEn?: string;

  @ApiPropertyOptional({ description: 'Product name (Arabic)' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  nameAr?: string;

  @ApiPropertyOptional({ description: 'Commercial/brand name' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  commercialName?: string;

  @ApiPropertyOptional({ description: 'Product description' })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiPropertyOptional({ description: 'Product type', enum: ProductType })
  @IsOptional()
  @IsEnum(ProductType)
  type?: ProductType;

  @ApiPropertyOptional({ description: 'ATCvet code (e.g., QJ01MA90)' })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  atcVetCode?: string;

  @ApiPropertyOptional({ description: 'Manufacturer name' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  manufacturer?: string;

  @ApiPropertyOptional({ description: 'Form (injectable, oral, topical, etc.)' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  form?: string;

  // Vaccine-specific fields (when type = vaccine)
  @ApiPropertyOptional({ description: 'Target disease (for vaccines)' })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  targetDisease?: string;

  @ApiPropertyOptional({ description: 'Immunity duration in days (for vaccines)' })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  immunityDurationDays?: number;

  @ApiPropertyOptional({ description: 'Notes' })
  @IsOptional()
  @IsString()
  notes?: string;

  @ApiPropertyOptional({ description: 'Is active', default: true })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;

  // Sync fields
  @ApiPropertyOptional({ description: 'Client creation timestamp' })
  @IsOptional()
  @IsDateString()
  created_at?: string;

  @ApiPropertyOptional({ description: 'Client update timestamp' })
  @IsOptional()
  @IsDateString()
  updated_at?: string;
}

// =============================================================================
// CREATE GLOBAL DTO - For admin creating global products (scope='global')
// =============================================================================
export class CreateGlobalProductDto extends CreateProductDto {
  @ApiProperty({ description: 'Unique product code (required for global)' })
  @IsString()
  @MaxLength(50)
  code: string;
}

// =============================================================================
// UPDATE DTO
// =============================================================================
export class UpdateProductDto {
  @ApiPropertyOptional({ description: 'Product name (French)' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  nameFr?: string;

  @ApiPropertyOptional({ description: 'Product name (English)' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  nameEn?: string;

  @ApiPropertyOptional({ description: 'Product name (Arabic)' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  nameAr?: string;

  @ApiPropertyOptional({ description: 'Commercial/brand name' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  commercialName?: string;

  @ApiPropertyOptional({ description: 'Product description' })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiPropertyOptional({ description: 'Product type', enum: ProductType })
  @IsOptional()
  @IsEnum(ProductType)
  type?: ProductType;

  @ApiPropertyOptional({ description: 'ATCvet code' })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  atcVetCode?: string;

  @ApiPropertyOptional({ description: 'Manufacturer name' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  manufacturer?: string;

  @ApiPropertyOptional({ description: 'Form' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  form?: string;

  @ApiPropertyOptional({ description: 'Target disease (for vaccines)' })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  targetDisease?: string;

  @ApiPropertyOptional({ description: 'Immunity duration in days' })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  immunityDurationDays?: number;

  @ApiPropertyOptional({ description: 'Notes' })
  @IsOptional()
  @IsString()
  notes?: string;

  @ApiPropertyOptional({ description: 'Is active' })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;

  @ApiPropertyOptional({ description: 'Version for conflict management' })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  version?: number;

  @ApiPropertyOptional({ description: 'Client update timestamp' })
  @IsOptional()
  @IsDateString()
  updated_at?: string;
}

// =============================================================================
// QUERY DTO - For filtering and pagination
// =============================================================================
export class QueryProductDto {
  @ApiPropertyOptional({ description: 'Search by name' })
  @IsOptional()
  @IsString()
  search?: string;

  @ApiPropertyOptional({
    description: 'Filter by scope (global, local, all)',
    enum: ['global', 'local', 'all'],
    default: 'all',
  })
  @IsOptional()
  @IsString()
  scope?: 'global' | 'local' | 'all';

  @ApiPropertyOptional({ description: 'Filter by product type', enum: ProductType })
  @IsOptional()
  @IsEnum(ProductType)
  type?: ProductType;

  @ApiPropertyOptional({ description: 'Filter by active status' })
  @IsOptional()
  @Type(() => Boolean)
  @IsBoolean()
  isActive?: boolean;

  @ApiPropertyOptional({ description: 'Filter vaccines only', default: false })
  @IsOptional()
  @Type(() => Boolean)
  @IsBoolean()
  vaccinesOnly?: boolean;

  @ApiPropertyOptional({ description: 'Page number', default: 1 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  page?: number;

  @ApiPropertyOptional({ description: 'Items per page', default: 50 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  limit?: number;

  @ApiPropertyOptional({ description: 'Sort field', default: 'nameFr' })
  @IsOptional()
  @IsString()
  sort?: string;

  @ApiPropertyOptional({ enum: ['asc', 'desc'], default: 'asc' })
  @IsOptional()
  @IsEnum(['asc', 'desc'])
  order?: 'asc' | 'desc';
}

// Export response DTO
export * from './product-response.dto';
