import {
  IsString,
  IsOptional,
  IsBoolean,
  IsUUID,
  IsNumber,
  IsInt,
  MaxLength,
  Min,
  IsDateString,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';

// =============================================================================
// CREATE DTO - For creating product packagings
// =============================================================================
export class CreateProductPackagingDto {
  @ApiPropertyOptional({ description: 'UUID generated by client (optional)' })
  @IsOptional()
  @IsUUID()
  id?: string;

  @ApiProperty({ description: 'Product ID' })
  @IsUUID()
  productId: string;

  @ApiProperty({ description: 'Country code (ISO 3166-1 alpha-2)', example: 'FR' })
  @IsString()
  @MaxLength(2)
  countryCode: string;

  @ApiProperty({ description: 'Concentration value', example: 100 })
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  concentration: number;

  @ApiProperty({ description: 'Concentration unit ID' })
  @IsUUID()
  concentrationUnitId: string;

  @ApiPropertyOptional({ description: 'Volume value', example: 100 })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  volume?: number;

  @ApiPropertyOptional({ description: 'Volume unit ID' })
  @IsOptional()
  @IsUUID()
  volumeUnitId?: string;

  @ApiProperty({ description: 'Packaging label', example: 'Flacon 100ml' })
  @IsString()
  @MaxLength(255)
  packagingLabel: string;

  @ApiPropertyOptional({ description: 'GTIN/EAN barcode' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  gtinEan?: string;

  @ApiPropertyOptional({ description: 'Marketing authorization number (AMM)' })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  numeroAMM?: string;

  @ApiPropertyOptional({ description: 'Is active', default: true })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;

  // Sync fields
  @ApiPropertyOptional({ description: 'Client creation timestamp' })
  @IsOptional()
  @IsDateString()
  created_at?: string;

  @ApiPropertyOptional({ description: 'Client update timestamp' })
  @IsOptional()
  @IsDateString()
  updated_at?: string;
}

// =============================================================================
// UPDATE DTO
// =============================================================================
export class UpdateProductPackagingDto {
  @ApiPropertyOptional({ description: 'Concentration value' })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  concentration?: number;

  @ApiPropertyOptional({ description: 'Concentration unit ID' })
  @IsOptional()
  @IsUUID()
  concentrationUnitId?: string;

  @ApiPropertyOptional({ description: 'Volume value' })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  volume?: number;

  @ApiPropertyOptional({ description: 'Volume unit ID' })
  @IsOptional()
  @IsUUID()
  volumeUnitId?: string;

  @ApiPropertyOptional({ description: 'Packaging label' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  packagingLabel?: string;

  @ApiPropertyOptional({ description: 'GTIN/EAN barcode' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  gtinEan?: string;

  @ApiPropertyOptional({ description: 'Marketing authorization number (AMM)' })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  numeroAMM?: string;

  @ApiPropertyOptional({ description: 'Is active' })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;

  @ApiPropertyOptional({ description: 'Version for conflict management' })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  version?: number;

  @ApiPropertyOptional({ description: 'Client update timestamp' })
  @IsOptional()
  @IsDateString()
  updated_at?: string;
}

// =============================================================================
// QUERY DTO - For filtering
// =============================================================================
export class QueryProductPackagingDto {
  @ApiPropertyOptional({ description: 'Filter by product ID' })
  @IsOptional()
  @IsUUID()
  productId?: string;

  @ApiPropertyOptional({ description: 'Filter by country code' })
  @IsOptional()
  @IsString()
  countryCode?: string;

  @ApiPropertyOptional({ description: 'Filter by GTIN/EAN' })
  @IsOptional()
  @IsString()
  gtinEan?: string;

  @ApiPropertyOptional({ description: 'Filter by active status' })
  @IsOptional()
  @Type(() => Boolean)
  @IsBoolean()
  isActive?: boolean;

  @ApiPropertyOptional({ description: 'Page number', default: 1 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  page?: number;

  @ApiPropertyOptional({ description: 'Items per page', default: 50 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  limit?: number;
}
